#!/bin/sh
CONFIG_VERSION="19.12.25"
# seg2delay='1'
# synfake='1'
# synfake_len='2'

# Цветовые коды
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}Настройка youtubeUnblock${NC}"
  if ! uci show youtubeUnblock | grep -q ".name='youtube_29.12.25'"; then
    while uci -q delete youtubeUnblock.@section[0]; do :; done
    uci set youtubeUnblock.youtubeUnblock.conf_strat='ui_flags'
    uci set youtubeUnblock.youtubeUnblock.packet_mark='32768'
    uci set youtubeUnblock.youtubeUnblock.queue_num='537'
    uci set youtubeUnblock.youtubeUnblock.silent='1'
    uci set youtubeUnblock.youtubeUnblock.no_ipv6='1'
    uci add youtubeUnblock section # =cfg02d2da
    uci set youtubeUnblock.@section[-1].name='youtube_29.12.25'
    uci set youtubeUnblock.@section[-1].enabled='1'
    uci set youtubeUnblock.@section[-1].tls_enabled='1'
    uci set youtubeUnblock.@section[-1].fake_sni='1'
    uci set youtubeUnblock.@section[-1].frag='tcp'
    uci set youtubeUnblock.@section[-1].frag_sni_reverse='1'
    uci set youtubeUnblock.@section[-1].frag_sni_faked='0'
    uci set youtubeUnblock.@section[-1].frag_middle_sni='1'
    uci set youtubeUnblock.@section[-1].frag_sni_pos='1'
    uci set youtubeUnblock.@section[-1].seg2delay='0'
    uci set youtubeUnblock.@section[-1].fk_winsize='0'
    uci set youtubeUnblock.@section[-1].synfake='0'
    uci set youtubeUnblock.@section[-1].all_domains='0'
    uci set youtubeUnblock.@section[-1].sni_detection='parse'
    uci add_list youtubeUnblock.@section[-1].sni_domains='googlevideo.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='ggpht.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='ytimg.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='youtube.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='play.google.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='youtu.be'
    uci add_list youtubeUnblock.@section[-1].sni_domains='googleapis.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='googleusercontent.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='gstatic.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='l.google.com'
    uci set youtubeUnblock.@section[-1].quic_drop='1'

    #if ! opkg list-installed | grep -q "^podkop "; then
      uci add youtubeUnblock section # =cfg03d2da
      uci set youtubeUnblock.@section[-1].name='other_zapret'
      uci set youtubeUnblock.@section[-1].enabled='1'
      uci set youtubeUnblock.@section[-1].tls_enabled='1'
      uci set youtubeUnblock.@section[-1].fake_sni='1'
      uci set youtubeUnblock.@section[-1].faking_strategy='pastseq'
      uci set youtubeUnblock.@section[-1].fake_sni_seq_len='1'
      uci set youtubeUnblock.@section[-1].fake_sni_type='default'
      uci set youtubeUnblock.@section[-1].frag='tcp'
      uci set youtubeUnblock.@section[-1].frag_sni_reverse='1'
      uci set youtubeUnblock.@section[-1].frag_sni_faked='0'
      uci set youtubeUnblock.@section[-1].frag_middle_sni='1'
      uci set youtubeUnblock.@section[-1].frag_sni_pos='1'
      uci set youtubeUnblock.@section[-1].seg2delay='0'
      uci set youtubeUnblock.@section[-1].fk_winsize='0'
      uci set youtubeUnblock.@section[-1].synfake='0'
      uci set youtubeUnblock.@section[-1].all_domains='0'
      uci set youtubeUnblock.@section[-1].sni_detection='parse'
      uci set youtubeUnblock.@section[-1].quic_drop='0'
      uci set youtubeUnblock.@section[-1].udp_mode='fake'
      uci set youtubeUnblock.@section[-1].udp_faking_strategy='none'
      uci set youtubeUnblock.@section[-1].udp_fake_seq_len='6'
      uci set youtubeUnblock.@section[-1].udp_fake_len='64'
      uci add_list youtubeUnblock.@section[-1].udp_dport_filter='50000-50100'
      uci set youtubeUnblock.@section[-1].udp_filter_quic='disabled'
      uci add_list youtubeUnblock.@section[-1].sni_domains='discord.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='discordapp.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='discord.gg'
      uci add_list youtubeUnblock.@section[-1].sni_domains='discordapp.net'
      uci add_list youtubeUnblock.@section[-1].sni_domains='discord.media'
      uci add_list youtubeUnblock.@section[-1].sni_domains='cdninstagram.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='instagram.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='ig.me'
      uci add_list youtubeUnblock.@section[-1].sni_domains='fbcdn.net'
      uci add_list youtubeUnblock.@section[-1].sni_domains='facebook.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='facebook.net'
      uci add_list youtubeUnblock.@section[-1].sni_domains='fb.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='threads.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='threads.net'
      uci add_list youtubeUnblock.@section[-1].sni_domains='rutracker.org'
      uci add_list youtubeUnblock.@section[-1].sni_domains='rutracker.net'
      uci add_list youtubeUnblock.@section[-1].sni_domains='rutracker.cc'
      uci add_list youtubeUnblock.@section[-1].sni_domains='rutor.info'
      uci add_list youtubeUnblock.@section[-1].sni_domains='rutor.is'
      uci add_list youtubeUnblock.@section[-1].sni_domains='nnmclub.to'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twitter.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='t.co'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twimg.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='ads-twitter.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='x.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='pscp.tv'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twtrdns.net'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twttr.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='periscope.tv'
      uci add_list youtubeUnblock.@section[-1].sni_domains='tweetdeck.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twitpic.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twitter.co'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twitterinc.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twitteroauth.com'
      uci add_list youtubeUnblock.@section[-1].sni_domains='twitterstat.us'
    #fi
    uci commit youtubeUnblock
  fi

  if ! uci show youtubeUnblock | grep -q ".name='CallsWhatsAppTelegram_19.12.25'"; then
    uci add youtubeUnblock section # =cfg03d2da
    uci set youtubeUnblock.@section[-1].name='CallsWhatsAppTelegram_19.12.25'
    uci set youtubeUnblock.@section[-1].enabled='1'
    uci set youtubeUnblock.@section[-1].tls_enabled='1'
    uci set youtubeUnblock.@section[-1].sni_detection='parse'
    uci set youtubeUnblock.@section[-1].fake_sni='1'
    uci set youtubeUnblock.@section[-1].faking_strategy='pastseq'
    uci set youtubeUnblock.@section[-1].fake_sni_seq_len='1'
    uci set youtubeUnblock.@section[-1].fake_sni_type='default'
    uci set youtubeUnblock.@section[-1].frag='tcp'
    uci set youtubeUnblock.@section[-1].frag_sni_reverse='1'
    uci set youtubeUnblock.@section[-1].frag_sni_faked='0'
    uci set youtubeUnblock.@section[-1].frag_middle_sni='1'
    uci set youtubeUnblock.@section[-1].frag_sni_pos='1'
    uci set youtubeUnblock.@section[-1].seg2delay='0'
    uci set youtubeUnblock.@section[-1].fk_winsize='0'
    uci set youtubeUnblock.@section[-1].synfake='0'
    uci set youtubeUnblock.@section[-1].all_domains='0'
    uci add_list youtubeUnblock.@section[-1].sni_domains='cdn-telegram.org'
    uci add_list youtubeUnblock.@section[-1].sni_domains='comments.app'
    uci add_list youtubeUnblock.@section[-1].sni_domains='contest.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='fragment.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='graph.org'
    uci add_list youtubeUnblock.@section[-1].sni_domains='quiz.directory'
    uci add_list youtubeUnblock.@section[-1].sni_domains='t.me'
    uci add_list youtubeUnblock.@section[-1].sni_domains='tdesktop.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telega.one'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telegra.ph'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telegram-cdn.org'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telegram.dog'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telegram.me'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telegram.org'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telegram.space'
    uci add_list youtubeUnblock.@section[-1].sni_domains='telesco.pe'
    uci add_list youtubeUnblock.@section[-1].sni_domains='tg.dev'
    uci add_list youtubeUnblock.@section[-1].sni_domains='tx.me'
    uci add_list youtubeUnblock.@section[-1].sni_domains='usercontent.dev'
    uci add_list youtubeUnblock.@section[-1].sni_domains='graph.facebook.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='whatsapp.biz'
    uci add_list youtubeUnblock.@section[-1].sni_domains='whatsapp.com'
    uci add_list youtubeUnblock.@section[-1].sni_domains='whatsapp.net'
    uci set youtubeUnblock.@section[-1].sni_detection='parse'
    uci set youtubeUnblock.@section[-1].quic_drop='0'
    uci set youtubeUnblock.@section[-1].udp_mode='fake'
    uci set youtubeUnblock.@section[-1].udp_faking_strategy='none'
    uci set youtubeUnblock.@section[-1].udp_fake_seq_len='6'
    uci set youtubeUnblock.@section[-1].udp_fake_len='64'
    uci set youtubeUnblock.@section[-1].udp_filter_quic='disabled'
    uci set youtubeUnblock.@section[-1].udp_stun_filter='1'
    uci commit youtubeUnblock
  fi
  
/etc/init.d/youtubeUnblock restart >/dev/null 2>&1